# Generated by Django 3.0.3 on 2020-02-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_level', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('SERVICE', 'SERVICE')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
